### ISSUE TITLE
Getting Key error 'value' while running

### ISSUE THREAD

**Issue by syedhamzaalee** [kiblee/tod0#11]
Running any command results in value error:

tod0
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user5\AppData\Roaming\Python\Python36\Scripts\tod0.exe\__main__.py", line 4, in <module>
  File "C:\Users\user5\AppData\Roaming\Python\Python36\site-packages\todocli\interface.py", line 80, in <module>
    load_folders()
  File "C:\Users\hamza\AppData\Roaming\Python\Python36\site-packages\todocli\interface.py", line 63, in load_folders
    folder_data = auth.list_and_update_folders()
  File "C:\Users\user5\AppData\Roaming\Python\Python36\site-packages\todocli\auth.py", line 125, in list_and_update_folders
    contents = parse_contents(o)
  File "C:\Users\user5\AppData\Roaming\Python\Python36\site-packages\todocli\auth.py", line 92, in parse_contents
    return json.loads(response.content.decode())["value"]

**Comment by kiblee** [comment]
Could you share the full traceback? I couldn't reproduce this error. 

However, it could be the OS - I haven't tested this on Windows. Was this your first run? Did the program ask you to enter your API information in a specific file?
