### ISSUE TITLE
ModuleNotFoundError on odata_system_query

### ISSUE THREAD

**Issue by kiblee** [kiblee/tod0#16]
**Describe the bug**
`ModuleNotFoundError` on `v0.6.0`.

**To Reproduce**
On `tod0` `v0.6.0`:
```
❯ todocli
Traceback (most recent call last):
  File "/temp-venv/bin/todocli", line 5, in <module>
    from todocli.cli import main
  File "/temp-venv/lib/python3.9/site-packages/todocli/cli.py", line 5, in <module>
    import todocli.todo_api as todo_api
  File "/temp-venv/lib/python3.9/site-packages/todocli/todo_api.py", line 9, in <module>
    from todocli import api_urls
  File "/temp-venv/lib/python3.9/site-packages/todocli/api_urls.py", line 1, in <module>
    from odata_system_query import ODataSystemQuery
ModuleNotFoundError: No module named 'odata_system_query'
```

**Comment by kiblee** [comment]
Hey @devzeb,

Version `0.6.0` is live on pip now but we must've missed this during review. Could you look into it? Thanks.

**Comment by devzeb** [comment]
Woops, I fixed it. See PR #17
