### ISSUE TITLE
KeyBindings Import Error

### ISSUE THREAD

**Issue by TestingBytes** [kiblee/tod0#26]
**Describe the bug**
Following the installation procedure in Windows Subsystem for Linx and I get the following error attempting to run "tod0":

```
Traceback (most recent call last):
  File "/usr/local/bin/tod0", line 11, in <module>
    load_entry_point('tod0==0.6.1', 'console_scripts', 'tod0')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/tod0-0.6.1-py3.7.egg/todocli/interface.py", line 4, in <module>
ImportError: cannot import name 'KeyBindings' from 'prompt_toolkit.key_binding' (/usr/lib/python3/dist-packages/prompt_toolkit/key_binding/__init__.py)
```

**Comment by kiblee** [comment]
Sorry, I couldn't reproduce this problem in Ubuntu under WSL. I will need more information or similar cases to fix this. Apologies.
